=== VeselinaTsatseva/Showroom/Showroom/validation.dtd
<!ELEMENT showroom (car)*>
        <!ELEMENT car (brand, model, year, price, picture, color, type, seats, doors, weight, dimensions, engine, euroClass, transmission, fuel, features, trunkCapacity)*>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price currency (лева|евро) "лева">
        <!ELEMENT picture (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT seats (#PCDATA)>
        <!ELEMENT doors (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT dimensions (length, width, height)*>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT width (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT engine (size, power, cylinders)*>
        <!ELEMENT size (#PCDATA)>
        <!ATTLIST size unit CDATA "см3">
        <!ELEMENT power (#PCDATA)>
        <!ATTLIST power unit CDATA "hp">
        <!ELEMENT cylinders (#PCDATA)>
        <!ELEMENT euroClass (#PCDATA)>
        <!ELEMENT transmission (gears)*>
        <!ATTLIST transmission type (автоматик|ръчна|полуавтоматик) "ръчна">
        <!ELEMENT gears (#PCDATA)>
        <!ELEMENT fuel (fuelConsumption, fuelType, tankCapacity)*>
        <!ELEMENT fuelConsumption (#PCDATA)>
        <!ATTLIST fuelConsumption unit CDATA "л/100км">
        <!ELEMENT fuelType (#PCDATA)>
        <!ELEMENT tankCapacity (#PCDATA)>
        <!ATTLIST tankCapacity unit (литра|галони) "литра">
        <!ELEMENT features (AC, ABS, rearCamera)*>
        <!ELEMENT AC (#PCDATA)>
        <!ELEMENT ABS (#PCDATA)>
        <!ELEMENT rearCamera (#PCDATA)>
        <!ELEMENT trunkCapacity (#PCDATA)>

=== VeselinaTsatseva/Showroom/Showroom/showroom5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
<car>
    <brand>Opel</brand>
    <model>Astra Sports Tourer</model>
    <year>2019</year>
    <price currency="лева">15800</price>
    <picture>https://4.bp.blogspot.com/-lV0U9Q_Gw6c/ViD9DCAYgrI/AAAAAAAAQIk/sCprjBtMzWY/s1600/opel-astra-sports-tourer-gris-mineral-k.png</picture>
    <color>Металик</color>
    <type>Комби</type>
    <seats>5</seats>
    <doors>5</doors>
    <weight>1295</weight>
    <dimensions>
        <length>4702</length>
        <width>1809</width>
        <height>1510</height>
    </dimensions>
    <engine>
        <size unit="см3">1.2</size>
        <power unit="hp">145</power>
        <cylinders>3</cylinders>
    </engine>
    <euroClass>6</euroClass>
    <transmission type="ръчна">
        <gears>5</gears>
    </transmission>
    <fuel>
        <fuelConsumption unit="л/100км">4.8</fuelConsumption>
        <fuelType>Бензин</fuelType>
        <tankCapacity unit="литра">48</tankCapacity>
    </fuel>
    <features>
        <AC>да</AC>
        <ABS>да</ABS>
        <rearCamera>да</rearCamera>
    </features>
    <trunkCapacity>540</trunkCapacity>
</car>
</showroom>

=== VeselinaTsatseva/Showroom/Showroom/showroom1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<?xml-stylesheet type="text/xml" href="to-HTML2.xsl" version="1.0" ?>-->
<!--<?xml-stylesheet type="text/xml" href="to-HTML2.xsl" version="1.0" ?>-->
<!--<?xml-stylesheet type="text/xml" href="to-XML2.xsl" version="1.0" ?>-->
<!--<?xml-stylesheet type="text/xml" href="to-XML2.xsl" version="1.0" ?>-->
<?xml-stylesheet type="text/xml" href="to-text1.xsl" version="1.0" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
<car>
    <brand>VW</brand>
    <model>T-Roc</model>
    <year>2017</year>
    <price currency="лева">43650</price>
    <picture>https://images.caradisiac.com/images/8/6/8/4/178684/S0-volkswagen-t-roc-un-diesel-puissant-arrive-604054.jpg</picture>
    <color>Черен</color>
    <type>SUV</type>
    <seats>5</seats>
    <doors>5</doors>
    <weight>1505</weight>
    <dimensions>
        <length>4234</length>
        <width>1819</width>
        <height>1573</height>
    </dimensions>
    <engine>
        <size unit="см3">2.0</size>
        <power unit="hp">150</power>
        <cylinders>4</cylinders>
    </engine>
    <euroClass>6</euroClass>
    <transmission type="ръчна">
        <gears>6</gears>
    </transmission>
    <fuel>
        <fuelConsumption unit="л/100км">5</fuelConsumption>
        <fuelType>Дизел</fuelType>
        <tankCapacity unit="литра">55</tankCapacity>
    </fuel>
    <features>
        <AC>да</AC>
        <ABS>да</ABS>
        <rearCamera>да</rearCamera>
    </features>
    <trunkCapacity>1237</trunkCapacity>
</car>

    <car>
        <brand>VW</brand>
        <model>Golf</model>
        <year>2010</year>
        <price currency="лева">12000</price>
        <picture>https://preview2.netcarshow.com/Volkswagen-Golf_GTD-2010-1600-12.jpg</picture>
        <color>Сив</color>
        <type>Хечбек</type>
        <seats>5</seats>
        <doors>5</doors>
        <weight>1154</weight>
        <dimensions>
            <length>4199</length>
            <width>1786</width>
            <height>1480</height>
        </dimensions>
        <engine>
            <size unit="см3">1.2</size>
            <power unit="hp">85</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="ръчна">
            <gears>5</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">5.5</fuelConsumption>
            <fuelType>Бензин</fuelType>
            <tankCapacity unit="литра">50</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>не</rearCamera>
        </features>
        <trunkCapacity>350</trunkCapacity>
    </car>

    <car>
        <brand>Toyota</brand>
        <model>CH-R</model>
        <year>2016</year>
        <price currency="лева">76800</price>
        <picture>https://cdn.wheel-size.com/automobile/body/toyota-c-hr-2016-2022-1630470478.7835937.jpg</picture>
        <color>Син</color>
        <type>SUV</type>
        <seats>5</seats>
        <doors>5</doors>
        <weight>1455</weight>
        <dimensions>
            <length>4390</length>
            <width>1795</width>
            <height>1555</height>
        </dimensions>
        <engine>
            <size unit="см3">1.8</size>
            <power unit="hp">122</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>6</euroClass>
        <transmission type="автоматик">
            <gears>7</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">5.3</fuelConsumption>
            <fuelType>Хибрид/Дизел</fuelType>
            <tankCapacity unit="литра">43</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>1164</trunkCapacity>
    </car>

    <car>
        <brand>VW</brand>
        <model>Tiguan</model>
        <year>2016</year>
        <price currency="лева">51000</price>
        <picture>https://images.hgmsites.net/hug/2015-volkswagen-tiguan_100475958_h.jpg</picture>
        <color>Бял</color>
        <type>SUV</type>
        <seats>5</seats>
        <doors>5</doors>
        <weight>1539</weight>
        <dimensions>
            <length>4486</length>
            <width>1829</width>
            <height>1632</height>
        </dimensions>
        <engine>
            <size unit="см3">2.0</size>
            <power unit="hp">150</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="ръчна">
            <gears>6</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">4.8</fuelConsumption>
            <fuelType>Дизел</fuelType>
            <tankCapacity unit="литра">58</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>520</trunkCapacity>
    </car>

    <car>
        <brand>BMW</brand>
        <model>X5</model>
        <year>2019</year>
        <price currency="лева">120000</price>
        <picture>https://www.tuningblog.eu/wp-content/uploads/2019/03/2019-G-Power-BMW-X5-xDrive50i-M50d-G05-Tuning-1.jpg</picture>
        <color>Черен</color>
        <type>SUV</type>
        <seats>5</seats>
        <doors>5/7</doors>
        <weight>2183</weight>
        <dimensions>
            <length>4935</length>
            <width>2004</width>
            <height>1745</height>
        </dimensions>
        <engine>
            <size unit="см3">3.0</size>
            <power unit="hp">335</power>
            <cylinders>6</cylinders>
        </engine>
        <euroClass>6</euroClass>
        <transmission type="автоматик">
            <gears>8</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">10.5</fuelConsumption>
            <fuelType>Бензин</fuelType>
            <tankCapacity unit="литра">83</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>650</trunkCapacity>
    </car>

    <car>
        <brand>Nissan</brand>
        <model>Qashqai</model>
        <year>2012</year>
        <price currency="лева">48000</price>
        <picture>https://preview2.netcarshow.com/Nissan-Qashqai-2012-hd.jpg</picture>
        <color>Червен</color>
        <type>SUV</type>
        <seats>5</seats>
        <doors>5</doors>
        <weight>1297</weight>
        <dimensions>
            <length>4331</length>
            <width>1783</width>
            <height>1615</height>
        </dimensions>
        <engine>
            <size unit="см3">1.6</size>
            <power unit="hp">114</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="ръчна">
            <gears>5</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">6.6</fuelConsumption>
            <fuelType>Бензин</fuelType>
            <tankCapacity unit="литра">65</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>388</trunkCapacity>
    </car>
</showroom>

=== VeselinaTsatseva/Showroom/Showroom/showroom3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
    <car>
        <brand>Land Rover</brand>
        <model>Range Rover Evoque</model>
        <year>2015</year>
        <price currency="лева">99123</price>
        <picture>http://carsot.com/images/land-rover-range-rover-i-1970-1996-suv-5-door-exterior-3.jpg</picture>
        <color>Бял</color>
        <type>SUV</type>
        <seats>5</seats>
        <doors>5</doors>
        <weight>1670</weight>
        <dimensions>
            <length>4365</length>
            <width>1900</width>
            <height>1635</height>
        </dimensions>
        <engine>
            <size unit="см3">2.2</size>
            <power unit="hp">190</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="автоматик">
            <gears>9</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">5.7</fuelConsumption>
            <fuelType>Дизел</fuelType>
            <tankCapacity unit="литра">60</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>575</trunkCapacity>
    </car>
</showroom>

=== VeselinaTsatseva/Showroom/Showroom/showroom2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
    <car>
        <brand>Toyota</brand>
        <model>Aygo</model>
        <year>2007</year>
        <price currency="лева">15800</price>
        <picture>https://www.carjunction.com/car_images2/40011_51883/42951875-1.jpg</picture>
        <color>Червен</color>
        <type>Хечбек</type>
        <seats>4</seats>
        <doors>5</doors>
        <weight>890</weight>
        <dimensions>
            <length>3410</length>
            <width>1615</width>
            <height>1465</height>
        </dimensions>
        <engine>
            <size unit="см3">1.4</size>
            <power unit="hp">54</power>
            <cylinders>4</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="ръчна">
            <gears>5</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">4.1</fuelConsumption>
            <fuelType>Дизел</fuelType>
            <tankCapacity unit="литра">35</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>не</rearCamera>
        </features>
        <trunkCapacity>168</trunkCapacity>
    </car>
</showroom>

=== VeselinaTsatseva/Showroom/Showroom/showroom4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
    <car>
        <brand>Mercedes-Benz</brand>
        <model>CLS</model>
        <year>2018</year>
        <price currency="лева">110444</price>
        <picture>https://www.masinipestoc.ro/images/cache/product_slider_large_thumb/uploads/images/car/mercedes-benz-cla-e6c708.png</picture>
        <color>Черен</color>
        <type>Купе</type>
        <seats>4</seats>
        <doors>4</doors>
        <weight>1860</weight>
        <dimensions>
            <length>4988</length>
            <width>1890</width>
            <height>1435</height>
        </dimensions>
        <engine>
            <size unit="см3">2.9</size>
            <power unit="hp">286</power>
            <cylinders>6</cylinders>
        </engine>
        <euroClass>6</euroClass>
        <transmission type="автоматик">
            <gears>9</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="L/100km">7</fuelConsumption>
            <fuelType>Дизел</fuelType>
            <tankCapacity unit="литра">50</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>520</trunkCapacity>
    </car>
</showroom>

=== VeselinaTsatseva/Showroom/Showroom/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE showroom SYSTEM "validation.dtd">

<showroom>
    <car>
        <brand>Renault</brand>
        <model>Clio</model>
        <year>2016</year>
        <price currency="евро">28444</price>
        <color>Червен</color>
        <type>Купе</type>
        <seats>5</seats>
        <doors>4</doors>
        <weight>1860</weight>
        <dimensions>
            <length>4988</length>
            <width>1890</width>
            <height>1435</height>
        </dimensions>
        <engine>
            <size unit="см3">1.7</size>
            <power unit="hp">140</power>
            <cylinders>6</cylinders>
        </engine>
        <euroClass>5</euroClass>
        <transmission type="ръчна">
            <gears>6</gears>
        </transmission>
        <fuel>
            <fuelConsumption unit="л/100км">7</fuelConsumption>
            <fuelType>Дизел</fuelType>
            <tankCapacity unit="литра">50</tankCapacity>
        </fuel>
        <features>
            <AC>да</AC>
            <ABS>да</ABS>
            <rearCamera>да</rearCamera>
        </features>
        <trunkCapacity>520</trunkCapacity>
    </car>
</showroom>
